### ISSUE TITLE
По текущему состоянию

### ISSUE THREAD

**Issue by KolosovKD** [PolarDL/J120-laboratornaya-rabota-no1#2]
1. Для оступа к настройкам вы везде используете клсс `ConfigIO` каждый раз читая настройки из файла. Логичнее один раз прочитать настройки из файла и сохранить их в памяти. У вас уже есть класс `Config` - сохраните настройки в его объекте:
_создаем новый `Config`_ **->** _он вызывает `ConfigIO`_ **->** _`ConfigIO` читает настройки из файла_ **->** _`Config` сохраняет настройки в переменную `configProperties`_.
при следующих обращениях в файл не лезет, просто смотрит что у него в `configProperties`.
1. Класс `OrderIO`:
-- строки 26-35: Странная конструкция:
`FileOutputStream fileOutputStream = new FileOutputStream("ListOfOrders.dat");
                fileOutputStream.close();`
Вы создаете `fileOutputStream` и тут же его закрываете. Это, наверно, лишнее.
1. Класс `ItemIO`:
-- Можно вместо сканера разбить прочитанную строку на части с помощью метода `split` класс `String`. 
`String[] values = line.split(";");`
1. Класс `OrderPositions`:
-- название класса не соотетствует содержимому - класс описывает одну позицию заказа (единственное число).
1. Класс `Order`:
-- строка 15: будет не очень удобно хранить список позиций заказа в обычном множестве - оно не гарантирует порядок элементов и не дает возможности доступа к отдельному элементу по индексу.

**Comment by PolarDL** [comment]
Как вижу, это просто повтор/ копия первого issue.
